Git_Branches/step6/sfdx-travelApprovalAPP/force-app/main/default/objects/public_rulestable__x/public_rulestable__x.object-meta.xml
<CustomObject>
    <description>public$rulestable</description>
    <externalDataSource>restWSRulesPostgres</externalDataSource>
    <externalName>public$rulestable</externalName>
    <label>public$rulestable</label>
    <pluralLabel>public$rulestable</pluralLabel>
</CustomObject>

Git_Branches/step6/sfdx-travelApprovalAPP/force-app/main/default/objects/public_rulestable__x/fields/description__c.field-meta.xml
<CustomField>
    <fullName>description__c</fullName>
    <description>description</description>
    <externalDeveloperName>description</externalDeveloperName>
    <label>description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/public_rulestable__x/fields/name__c.field-meta.xml
<CustomField>
    <fullName>name__c</fullName>
    <description>name</description>
    <externalDeveloperName>name</externalDeveloperName>
    <label>name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git_Branches/step6/sfdx-travelApprovalAPP/force-app/main/default/objects/public_rulestable__x/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <description>type</description>
    <externalDeveloperName>type</externalDeveloperName>
    <label>type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Rules_CTRL_TEST.cls
@isTest
public class Rules_CTRL_TEST {

    // -------------------------------------
    // getRulesListFctTest() method
    // -------------------------------------  
    static testMethod void getRulesListFctTest() {
        // public_rulestable__x Data
        //public_rulestable__x oRule = new public_rulestable__x(name__c='Rule1Test', type__c='TypeTest', description__c='DescriptionTest');
        //Database.insertImmediate(oRule);
        
        // Rules controller test
        list<public_rulestable__x> lRules = new list<public_rulestable__x>();
        lRules = Rules_CTRL.getRulesListFct('TypeTest');
        
        //Database.deleteImmediate(oRule);
    }
}